# User Controller

include Hampusn::MessageCache::Models

module Hampusn
  module MessageCache
    module Controllers
      class UserController < Hampusn::MessageCache::Base

        helpers Hampusn::MessageCache::Helpers::UserHelpers

        post '/user/login' do
          # Handle authentication
        end

        get '/user/register' do
          # Register view with form
          @email = params[:email]
          @registration_key = params[:key]

          haml :register
        end

        post '/user/register' do
          request = Request.where(email: params[:email], registration_key: params[:registration_key], approved: true).take

          unless request.nil?
            salt     = generate_new_salt
            password = generate_password_hash params[:password], salt

            user = User.new

            user.username = params[:username]
            user.email    = params[:email]
            user.password = password
            user.salt     = salt
            # user.key is left out since that should be generated by the user.

            user_saved = user.save

            if user_saved
              request.destroy
              redirect '/'
            end
          end

          redirect '/user/register'
        end

        post '/user/reset-password' do
          # ...
        end

      end
    end
  end
end
